server:
  port: 8081
#  servlet:
#    context-path: /app

logging:
  config: classpath:logback-spring.xml

mybatis.mapper-locations: classpath*:mapper/*.xml

spring:
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
  http:
    encoding:
      force: true
      charset: UTF-8
      #数据库设置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/em?useUnicode:true&characterEncoding:utf8&autoReconnect:true&useSSL:true&allowMultiQueries=true
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点